### ISSUE TITLE
inference code on single video？

### ISSUE THREAD

**Issue by dragen1860** [alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates#10]
Dear all:
  thanks for sharing this great work!  I read the readme.md carefully and could not found any tips on inference on single video? anyone share the inference code?

**Comment by alexandrosstergiou** [comment]
Hi @dragen1860,

There is no explicit script for inference. To solely perform evaluation, you can modify `train/model.py` by commenting out lines 378-582, i.e.: https://github.com/alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates/blob/1641b59b73c951a5b05d17b5528894ae73a014b8/train/model.py#L378-L582
And adding 
```python 
break
```
at line 657

**Comment by dragen1860** [comment]
looks reasonable! thanks for your tips.
