### ISSUE TITLE
The SRTG part may won't be update

### ISSUE THREAD

**Issue by RongchangLi** [alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates#2]
As the code and paper show, if TG gate keep close,oprations on the input of pool and lstm part won't move forward. And it means when we do back  propagation, parameters of lstm part and TG gate won't be updated, which  can easily happen. So how  did you solve the problem? or did I missing something?

**Comment by alexandrosstergiou** [comment]
Yes, the main mindset is to only use information that is cyclic-consistent. Therefore, the LSTM parts of the network are only updated _if and only if_ they are consistent with the spatially pooled version of the activations. (You can think of this as worse-case scenario with only using the backbone CNN). For most experiments, the gates were inactive for the first 30~50 epochs, thus the weights of the LSTM would not be completely random when the gates are indeed active for the rest of the training.

Best,
Alex

**Comment by RongchangLi** [comment]
> Yes, the main mindset is to only use information that is cyclic-consistent. Therefore, the LSTM parts of the network are only updated _if and only if_ they are consistent with the spatially pooled version of the activations. (You can think of this as worse-case scenario with only using the backbone CNN). For most experiments, the gates were inactive for the first 30~50 epochs, thus the weights of the LSTM would not be completely random when the gates are indeed active for the rest of the training.
> 
> Best,
> Alex

Ha, the result seems very reasonable. Thanks for your reply and your work(both the code and paper) did inspire me much.
