### ISSUE TITLE
All the batches are not cyclic consistent when using my own dataset

### ISSUE THREAD

**Issue by zzwei1** [alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates#4]
Hello, thanks for the paper and code. 
I'm doing some research on gesture recognition using FMCW radar. It's similar to video action recognition because the radar data I use is a video-like(3 channels pics, 32 frames) style.
When I tring to use the SRTG on my own radar data set, all the batches are not cyclic consistent, that is to say, the function soft_nnc returns to an empty array. So when I set the 'gate' open, the program cannot continue to run.
Is there some advice ?
Looking forward to your reply!

**Comment by alexandrosstergiou** [comment]
Hi @zzwei1,
I think in cases that the data are not cyclic consistent it would make more sense to simply use the Squeeze and Recursion blocks without the cyclic-consistency gating mechanism (i.e. setting the `gates` parameter to `False`). This way you can regularise/calibrate the activation maps based on information from the entire video.

I do not know if it would be sensible for your data, but If you still want to use cyclic-consistency, you could make something like a hybrid training scheme where the first x epochs you do not use the gates and then for the last y epochs you enable the gates.

Hope that any of the above ideas are proven useful, and thanks for using the code.

Best,
Alex

**Comment by alexandrosstergiou** [comment]
Will close this issue for now due to inactivity
