### ISSUE TITLE
Pretrained model release

### ISSUE THREAD

**Issue by simcity429** [alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates#5]
Hello! First, thank you for providing the great model. I'm desperately looking for the pretrained model for the HACS dataset, but I can hardly find one. Due to my computational resource, I cannot train it from scratch. When can I get the pretrained weight of your network?

**Comment by alexandrosstergiou** [comment]
Hi @simcity429,

The pre-trained models (trained on half-precision) on HACS are now available with the latest commit ([`33bbc7a`](https://github.com/alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates/tree/33bbc7a3aed42890390d6451902d9776ea727baa)). More updates to come once I have fully exhausted all options for making the models available for `float32` precision -- and being less dependant on `apex`.

Best,
Alex

**Comment by mzhou52** [comment]
Thanks a lot. I'm also desperately looking for the pretrained models on HACS !
