### ISSUE TITLE
Hew to get softpool_cuda

### ISSUE THREAD

**Issue by OValery16** [alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates#7]
Thank for this very nice work. 

I would to test your work. How to get softpool_cuda library ?

**Comment by alexandrosstergiou** [comment]
Hi @OValery16,

You can get softpool from [this repo](https://github.com/alexandrosstergiou/SoftPool) and following the installation steps. Alternatively, you can also comment out the corresponding lines and use standard pooling operations.

Best,
Alex

**Comment by OValery16** [comment]
Hi @alexandrosstergiou,

Thanks for your very quick reply. 

I am currently reading your paper about SoftPool (https://arxiv.org/pdf/2101.00440.pdf). I have to recognize I am quite impressed. The intuition behind SoftPool is really interesting.

Thank you for your work.

Olivier

**Comment by alexandrosstergiou** [comment]
Thank you very much! If you have any problems with any of the projects feel free to open a new issue on either of the repos.

Best,
Alex
