### ISSUE TITLE
frames.db file has no record

### ISSUE THREAD

**Issue by paden118** [alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates#9]
I has tried to use the convert function twice，but still frames.db file has no record，I don't know why?

**Comment by alexandrosstergiou** [comment]
Hi @paden118 ,

Can you provide the structure of your video directory that you are trying to convert and the code snipped where `convert()` is called? There are also *Dataset structure* and *Usage* sections of [`dataset2database/README.md`](https://github.com/alexandrosstergiou/dataset2database) which would be worth reading through.

**Comment by paden118** [comment]
My video directory structure such as:
<UCF-101>    
  │
  └──<YoYo>
  │     │
  │     │─── v_YoYo_g01_c01.avi
  │     │─── v_YoYo_g01_c02.avi
  │     │─── ...
         ...
Then I  install dataset2database and use this code to convert：
from dataset2database import convert

convert(my_dataset_dir, my_target_dir)

the result is that frames extraction is well, and the frames.db file is also created，but when I run train_ucf101.py，it shows that Ithere hasn't n_frames file, so I check the directory and README.md, and find that it maybe run num_frames.py to generate n_frames file, so I run it , unfortunately the print shows xxxx does not have any frames. So I download SQLiteStudio  to check it. to my surprise, the frames.db file has no record. I basically operate according to README.md and Issues.

And I operate on a Ubuntu system with two 2080ti graphics cards.

I look forward to your reply. My English is not well, so my reply will be a little slow. Please understand.


> Hi @paden118 ,
> 
> Can you provide the structure of your video directory that you are trying to convert and the code snipped where `convert()` is called? There are also _Dataset structure_ and _Usage_ sections of [`dataset2database/README.md`](https://github.com/alexandrosstergiou/dataset2database) which would be worth reading through.

**Comment by paden118** [comment]
My video directory structure such as:
<UCF-101>    
  │
  └──<YoYo>
  │     │
  │     │─── v_YoYo_g01_c01.avi
  │     │─── v_YoYo_g01_c02.avi
  │     │─── ...
         ...
Then I  install dataset2database and use this code to convert：
from dataset2database import convert

convert(my_dataset_dir, my_target_dir)

the result is that frames extraction is well, and the frames.db file is also created，but when I run train_ucf101.py，it shows that Ithere hasn't n_frames file, so I check the directory and README.md, and find that it maybe run num_frames.py to generate n_frames file, so I run it , unfortunately the print shows xxxx does not have any frames. So I download SQLiteStudio  to check it. to my surprise, the frames.db file has no record. I basically operate according to README.md and Issues.

And I operate on a Ubuntu system with two 2080ti graphics cards.

I look forward to your reply. My English is not well, so my reply will be a little slow. Please understand.

**Comment by paden118** [comment]
My video directory structure such as:

![image](https://user-images.githubusercontent.com/54985444/141965243-92855782-a7c2-46e9-b95c-d733581d117f.png)

Then I  install dataset2database and use this code to convert:

from dataset2database import convert

convert(my_dataset_dir, my_target_dir)

The result is that frames extraction is well, and the frames.db file is also created，but when I run train_ucf101.py，it shows that Ithere hasn't n_frames file, so I check the directory and README.md, and find that it maybe run num_frames.py to generate n_frames file, so I run it , unfortunately the print shows xxxx does not have any frames. So I download SQLiteStudio  to check it. to my surprise, the frames.db file has no record. I basically operate according to README.md and Issues.

And I operate on a Ubuntu system with two 2080ti graphics cards.

I look forward to your reply. My English is not well, so my reply will be a little slow. Please understand.

**Comment by alexandrosstergiou** [comment]
Can you go to the directory that UCF-101 is stored and execute 
```python -c "from dataset2database import convert; convert('UCF-101','UCF-101_videos')"```

This should create a new directory `UCF-101_videos` with the SQL `.db` files.

**Comment by paden118** [comment]
Yes，it works.There may be other questions to ask you next. Thanks for the answer.
